import type {
  AnnouncementRecord,
  AppointmentRecord,
  AbuseEvent,
  AccessRule,
  ApiCredential,
  AuditLogEntry,
  Campaign,
  Checkpoint,
  CheckoutQuestion,
  ConversionReport,
  CustomerSegment,
  DiscountCampaign,
  DynamicPricingRule,
  EventRecord,
  ExhibitorBooth,
  FinanceExport,
  FraudFlag,
  IntegrationConnection,
  InventoryHold,
  IssuedTicket,
  LivePoll,
  ManagedOrganization,
  MatchmakingProfile,
  MembershipPlan,
  NotificationChannel,
  OfflineScanEntry,
  OrderRecord,
  Organization,
  OrgSettings,
  PresaleCode,
  PriorityGroup,
  PurchaseLimitRule,
  QueueSnapshot,
  ReconciliationRun,
  ReEntryRecord,
  ReferralLink,
  ResaleListing,
  ScanDevice,
  SessionRecord,
  SpeakerProfile,
  SponsorProfile,
  SponsorPlacement,
  SsoConfiguration,
  SurveyRecord,
  TaxProfile,
  TeamMember,
  TicketTier,
  Venue,
  WaitingRoomEntry,
  WebhookEndpoint,
  UpgradeOffer,
} from './domain';
import type { AppDatabase } from './schema';
import { EVENTHUB_SCHEMA_VERSION } from './schema';

export const currentOrganization: Organization = {
  id: 'org_eventhub_nz',
  name: 'EventHub Pacific',
  slug: 'eventhub-pacific',
  timezone: 'Pacific/Auckland',
  region: 'NZ / AU',
  plan: 'growth',
  enabledPacks: ['standard', 'finance', 'operations', 'growth', 'conference', 'enterprise', 'monetization'],
};

export const currentUser: TeamMember = {
  id: 'user_001',
  name: 'Tom Omaet',
  email: 'tom@omaetgroup.co.nz',
  role: 'super_admin',
  scope: 'All organizations',
  lastActive: 'just now',
};

export const teamMembers: TeamMember[] = [
  currentUser,
  {
    id: 'user_002',
    name: 'Mia Jordan',
    email: 'mia@eventhub.io',
    role: 'organizer',
    scope: 'Auckland Summer Series',
    lastActive: '18 minutes ago',
  },
  {
    id: 'user_003',
    name: 'Riley Chen',
    email: 'riley@eventhub.io',
    role: 'venue_manager',
    scope: 'Harbour Hall',
    lastActive: '47 minutes ago',
  },
  {
    id: 'user_004',
    name: 'Noa Patel',
    email: 'noa@eventhub.io',
    role: 'staff',
    scope: 'East Gate / Check-in',
    lastActive: '5 minutes ago',
  },
];

export const venues: Venue[] = [
  {
    id: 'venue_001',
    name: 'Harbour Hall',
    address: '1 Quay Street',
    city: 'Auckland',
    country: 'NZ',
    capacity: 4200,
    zones: ['GA Floor', 'VIP Lounge', 'North Seating'],
    managerId: 'user_003',
    manager: 'Riley Chen',
    createdAt: '2026-01-10 09:00',
  },
  {
    id: 'venue_002',
    name: 'K Road Yard',
    address: '237 Karangahape Road',
    city: 'Auckland',
    country: 'NZ',
    capacity: 1800,
    zones: ['Courtyard', 'Terrace', 'Backstage'],
    managerId: 'user_002',
    manager: 'Mia Jordan',
    createdAt: '2026-01-15 11:30',
  },
  {
    id: 'venue_003',
    name: 'Wellington Pavilion',
    address: '55 Cable Street',
    city: 'Wellington',
    country: 'NZ',
    capacity: 2600,
    zones: ['Main Bowl', 'West Club', 'Entry A'],
    managerId: 'user_003',
    manager: 'Aroha Te Kani',
    createdAt: '2026-02-01 08:00',
  },
  {
    id: 'venue_004',
    name: 'SkyCity Theatre',
    address: '88 Federal Street',
    city: 'Auckland',
    country: 'NZ',
    capacity: 700,
    zones: ['Stalls', 'Mezzanine', 'Circle'],
    managerId: 'user_003',
    manager: 'Riley Chen',
    createdAt: '2026-01-22 10:00',
  },
  {
    id: 'venue_005',
    name: 'Michael Fowler Centre',
    address: '111 Wakefield Street',
    city: 'Wellington',
    country: 'NZ',
    capacity: 2500,
    zones: ['Stalls', 'Circle A', 'Circle B', 'Gallery'],
    managerId: 'user_003',
    manager: 'Aroha Te Kani',
    createdAt: '2026-02-10 09:00',
  },
];

export const events: EventRecord[] = [
  {
    id: 'evt_001',
    name: 'Auckland Summer Series',
    description: 'The premier outdoor summer festival series in Auckland, featuring international and local acts across three stages.',
    status: 'on_sale',
    startsAt: '2026-11-14 19:00',
    endsAt: '2026-11-14 23:59',
    venueId: 'venue_001',
    organizerId: 'user_002',
    category: 'Festival',
    ticketsSold: 3128,
    grossRevenue: 238420,
    createdAt: '2026-03-01 10:00',
  },
  {
    id: 'evt_002',
    name: 'Signal Conference 2026',
    description: 'New Zealand\'s leading technology and innovation conference, bringing together leaders from across the Pacific.',
    status: 'draft',
    startsAt: '2026-09-03 08:30',
    endsAt: '2026-09-04 17:00',
    venueId: 'venue_003',
    organizerId: 'user_002',
    category: 'Conference',
    ticketsSold: 0,
    grossRevenue: 0,
    createdAt: '2026-04-10 14:00',
  },
  {
    id: 'evt_003',
    name: 'Midnight Sessions',
    description: 'Late-night club event showcasing emerging electronic music talent in an intimate venue setting.',
    status: 'live',
    startsAt: '2026-04-19 21:00',
    endsAt: '2026-04-20 03:00',
    venueId: 'venue_002',
    organizerId: 'user_002',
    category: 'Club Night',
    ticketsSold: 1486,
    grossRevenue: 112360,
    createdAt: '2026-03-28 09:00',
  },
  {
    id: 'evt_004',
    name: 'Pacific Groove Festival',
    description: 'Three days of world music, Polynesian beats, and Pacific Island culture spread across the lawns of Wellington Pavilion. Featuring headline artists from Fiji, Samoa, Tonga, and New Zealand.',
    status: 'on_sale',
    startsAt: '2026-12-05 14:00',
    endsAt: '2026-12-07 23:00',
    venueId: 'venue_003',
    organizerId: 'user_002',
    category: 'Festival',
    ticketsSold: 2840,
    grossRevenue: 341200,
    createdAt: '2026-03-15 09:00',
  },
  {
    id: 'evt_005',
    name: 'Design Forward Summit',
    description: 'Two days of product design, brand strategy, and creative technology talks from New Zealand and international practitioners. Workshop sessions, portfolio critiques, and networking dinners included.',
    status: 'on_sale',
    startsAt: '2026-08-20 09:00',
    endsAt: '2026-08-21 17:30',
    venueId: 'venue_005',
    organizerId: 'user_002',
    category: 'Conference',
    ticketsSold: 610,
    grossRevenue: 122000,
    createdAt: '2026-04-01 11:00',
  },
  {
    id: 'evt_006',
    name: 'Harbour Nights Comedy',
    description: 'Auckland\'s favourite comedy night returns with a stellar lineup of local headliners and international guests. Three acts, two interval bars, and one unforgettable evening at SkyCity Theatre.',
    status: 'on_sale',
    startsAt: '2026-06-13 19:30',
    endsAt: '2026-06-13 22:30',
    venueId: 'venue_004',
    organizerId: 'user_002',
    category: 'Comedy',
    ticketsSold: 480,
    grossRevenue: 43200,
    createdAt: '2026-04-05 13:00',
  },
  {
    id: 'evt_007',
    name: 'Dusk to Dawn',
    description: 'An all-night electronic music experience at K Road Yard. Featuring four rooms, twelve selectors, and a sound system built for the serious listener.',
    status: 'on_sale',
    startsAt: '2026-05-24 22:00',
    endsAt: '2026-05-25 06:00',
    venueId: 'venue_002',
    organizerId: 'user_002',
    category: 'Club Night',
    ticketsSold: 920,
    grossRevenue: 62560,
    createdAt: '2026-04-10 16:00',
  },
  {
    id: 'evt_008',
    name: 'Matariki Gala Evening',
    description: 'A formal dinner and cultural celebration marking Matariki, the Māori New Year. Five-course menu by award-winning chefs, live taonga pūoro performance, and guest speakers on Māori astronomy.',
    status: 'on_sale',
    startsAt: '2026-06-27 18:30',
    endsAt: '2026-06-27 23:30',
    venueId: 'venue_005',
    organizerId: 'user_002',
    category: 'Gala',
    ticketsSold: 180,
    grossRevenue: 54000,
    createdAt: '2026-04-12 10:00',
  },
];

export const ticketTiers: TicketTier[] = [
  {
    id: 'tier_001',
    eventId: 'evt_001',
    name: 'General Admission',
    kind: 'general_admission',
    price: 89,
    inventory: 3000,
    sold: 2210,
    description: 'Access to all GA floor areas and outdoor stages.',
  },
  {
    id: 'tier_002',
    eventId: 'evt_001',
    name: 'VIP Deck',
    kind: 'vip',
    price: 189,
    inventory: 400,
    sold: 356,
    description: 'Elevated viewing deck with complimentary bar and dedicated entry.',
  },
  {
    id: 'tier_003',
    eventId: 'evt_003',
    name: 'Timed Entry Wave B',
    kind: 'timed_entry',
    price: 58,
    inventory: 500,
    sold: 412,
    description: 'Entry window 22:00–23:00. Standard access to all areas.',
  },
  {
    id: 'tier_004',
    eventId: 'evt_004',
    name: 'Weekend Pass',
    kind: 'general_admission',
    price: 120,
    inventory: 2000,
    sold: 1640,
    description: 'Access to all three days and all stages.',
  },
  {
    id: 'tier_005',
    eventId: 'evt_004',
    name: 'VIP Wristband',
    kind: 'vip',
    price: 280,
    inventory: 300,
    sold: 210,
    description: 'Premium viewing areas, backstage access, and artist meet & greet on Day 1.',
  },
  {
    id: 'tier_006',
    eventId: 'evt_005',
    name: 'General Delegate',
    kind: 'general_admission',
    price: 200,
    inventory: 400,
    sold: 310,
    description: 'Full two-day access, workshop sessions, and networking dinner.',
  },
  {
    id: 'tier_007',
    eventId: 'evt_005',
    name: 'Studio Pass',
    kind: 'vip',
    price: 480,
    inventory: 100,
    sold: 88,
    description: 'All General Delegate benefits plus portfolio critique session and speaker dinners.',
  },
  {
    id: 'tier_008',
    eventId: 'evt_006',
    name: 'Standard Seating',
    kind: 'reserved_seating',
    price: 55,
    inventory: 500,
    sold: 360,
    description: 'Reserved seat in the Stalls.',
  },
  {
    id: 'tier_009',
    eventId: 'evt_006',
    name: 'Mezzanine & Drinks',
    kind: 'vip',
    price: 90,
    inventory: 120,
    sold: 92,
    description: 'Elevated view with a welcome drink and reserved Mezzanine seating.',
  },
  {
    id: 'tier_010',
    eventId: 'evt_007',
    name: 'Early Entry',
    kind: 'timed_entry',
    price: 55,
    inventory: 300,
    sold: 300,
    description: 'Entry from 22:00. Early access to all rooms.',
  },
  {
    id: 'tier_011',
    eventId: 'evt_007',
    name: 'General Entry',
    kind: 'general_admission',
    price: 68,
    inventory: 700,
    sold: 620,
    description: 'Entry from 23:30. Access to all four rooms.',
  },
  {
    id: 'tier_012',
    eventId: 'evt_008',
    name: 'Dining Seat',
    kind: 'reserved_seating',
    price: 300,
    inventory: 160,
    sold: 140,
    description: 'Five-course dinner, live performance, and guest speaker programme.',
  },
  {
    id: 'tier_013',
    eventId: 'evt_008',
    name: 'Patron Table (10)',
    kind: 'vip',
    price: 3500,
    inventory: 4,
    sold: 4,
    description: 'Reserved table for 10. Includes pre-dinner reception with artists.',
  },
];

export const orders: OrderRecord[] = [
  {
    id: 'ord_1001',
    eventId: 'evt_001',
    tierId: 'tier_001',
    buyerName: 'Leah Thompson',
    buyerEmail: 'leah@example.com',
    total: 356,
    quantity: 4,
    status: 'paid',
    createdAt: '2026-04-19 18:10',
  },
  {
    id: 'ord_1002',
    eventId: 'evt_003',
    tierId: 'tier_003',
    buyerName: 'Finn Roberts',
    buyerEmail: 'finn@example.com',
    total: 116,
    quantity: 2,
    status: 'paid',
    createdAt: '2026-04-19 18:34',
  },
  {
    id: 'ord_1003',
    eventId: 'evt_001',
    tierId: 'tier_002',
    buyerName: 'Ava Ngata',
    buyerEmail: 'ava@example.com',
    total: 189,
    quantity: 1,
    status: 'pending',
    createdAt: '2026-04-19 19:02',
  },
];

export const issuedTickets: IssuedTicket[] = [
  {
    id: 'tkt_0001',
    orderId: 'ord_1001',
    tierId: 'tier_001',
    eventId: 'evt_001',
    holderName: 'Leah Thompson',
    holderEmail: 'leah@example.com',
    qrPayload: 'EVTHB-EVT001-TKT0001-A7F2',
    status: 'valid',
    issuedAt: '2026-04-19 18:11',
  },
  {
    id: 'tkt_0002',
    orderId: 'ord_1002',
    tierId: 'tier_003',
    eventId: 'evt_003',
    holderName: 'Finn Roberts',
    holderEmail: 'finn@example.com',
    qrPayload: 'EVTHB-EVT003-TKT0002-B3C9',
    status: 'used',
    issuedAt: '2026-04-19 18:35',
    scannedAt: '2026-04-19 22:04',
    scannedGate: 'East Gate',
  },
  {
    id: 'tkt_0003',
    orderId: 'ord_1002',
    tierId: 'tier_003',
    eventId: 'evt_003',
    holderName: 'Finn Roberts',
    holderEmail: 'finn@example.com',
    qrPayload: 'EVTHB-EVT003-TKT0003-D1E8',
    status: 'valid',
    issuedAt: '2026-04-19 18:35',
  },
];

export const checkpoints: Checkpoint[] = [
  { gate: 'East Gate',    eventId: 'evt_003', scanned: 1128, admitted: 1116, denied: 12, offlineDevices: 0, reAdmissions: 22 },
  { gate: 'VIP Lounge',  eventId: 'evt_003', scanned: 244,  admitted: 241,  denied: 3,  offlineDevices: 0, reAdmissions: 6  },
  { gate: 'North Seating', eventId: 'evt_003', scanned: 684, admitted: 677, denied: 7, offlineDevices: 1, reAdmissions: 14 },
];

export const devices: ScanDevice[] = [
  {
    id: 'dev_001',
    name: 'East Gate iPad',
    gate: 'East Gate',
    eventId: 'evt_003',
    operatorId: 'user_004',
    status: 'online',
    lastSeen: '2026-04-19 22:10',
    pendingScans: 0,
  },
  {
    id: 'dev_002',
    name: 'VIP Scanner',
    gate: 'VIP Lounge',
    eventId: 'evt_003',
    operatorId: 'user_003',
    status: 'online',
    lastSeen: '2026-04-19 22:08',
    pendingScans: 0,
  },
  {
    id: 'dev_003',
    name: 'North Handheld',
    gate: 'North Seating',
    eventId: 'evt_003',
    operatorId: 'user_004',
    status: 'offline',
    lastSeen: '2026-04-19 21:42',
    pendingScans: 3,
  },
];

export const accessRules: AccessRule[] = [
  {
    id: 'rule_001',
    eventId: 'evt_001',
    gate: 'VIP Lounge',
    label: 'VIP only',
    allowedTierIds: ['tier_002'],
    allowedKinds: ['vip'],
    requiresAccreditation: false,
    notes: 'GA tickets are not valid at this entrance.',
  },
  {
    id: 'rule_002',
    eventId: 'evt_001',
    gate: 'East Gate',
    label: 'GA + VIP',
    allowedTierIds: ['tier_001', 'tier_002'],
    allowedKinds: [],
    requiresAccreditation: false,
  },
  {
    id: 'rule_003',
    eventId: 'evt_003',
    gate: 'VIP Lounge',
    label: 'VIP only — Midnight Sessions',
    allowedTierIds: [],
    allowedKinds: ['vip'],
    requiresAccreditation: true,
    notes: 'Staff use West Entry. Accreditation wristband required.',
  },
];

export const offlineQueue: OfflineScanEntry[] = [
  {
    id: 'off_001',
    qrPayload: 'EVTHB-EVT003-TKT0003-D1E8',
    gate: 'North Seating',
    deviceId: 'dev_003',
    eventId: 'evt_003',
    scannedAt: '2026-04-19 21:38',
    synced: false,
  },
  {
    id: 'off_002',
    qrPayload: 'EVTHB-EVT003-TKTAAAA-1234',
    gate: 'North Seating',
    deviceId: 'dev_003',
    eventId: 'evt_003',
    scannedAt: '2026-04-19 21:41',
    synced: false,
  },
  {
    id: 'off_003',
    qrPayload: 'EVTHB-EVT003-TKTBBBB-5678',
    gate: 'North Seating',
    deviceId: 'dev_003',
    eventId: 'evt_003',
    scannedAt: '2026-04-19 21:43',
    synced: false,
  },
];

export const reEntryRecords: ReEntryRecord[] = [
  {
    id: 'reentry_001',
    ticketId: 'tkt_0001',
    holderName: 'Leah Thompson',
    eventId: 'evt_001',
    gate: 'East Gate',
    passedOutAt: '2026-04-19 20:15',
    readmittedAt: '2026-04-19 20:48',
    operatorId: 'user_004',
  },
  {
    id: 'reentry_002',
    ticketId: 'tkt_0002',
    holderName: 'Finn Roberts',
    eventId: 'evt_003',
    gate: 'East Gate',
    passedOutAt: '2026-04-19 22:18',
    operatorId: 'user_004',
  },
];

export const auditLog: AuditLogEntry[] = [
  {
    id: 'log_001',
    actor: 'Tom Omaet',
    action: 'Updated ticket inventory',
    target: 'Auckland Summer Series / VIP Deck',
    timestamp: '2026-04-19 18:04',
    severity: 'info',
  },
  {
    id: 'log_002',
    actor: 'Riley Chen',
    action: 'Approved venue access rule',
    target: 'Harbour Hall / North Seating',
    timestamp: '2026-04-19 18:22',
    severity: 'warning',
  },
  {
    id: 'log_003',
    actor: 'System',
    action: 'Offline scanner re-synced',
    target: 'Midnight Sessions / East Gate',
    timestamp: '2026-04-19 18:47',
    severity: 'critical',
  },
];

export const notificationChannels: NotificationChannel[] = [
  {
    channel: 'email',
    status: 'needs_config',
    note: 'Add transactional sender and templates for order confirmations.',
  },
  {
    channel: 'payments',
    status: 'needs_config',
    note: 'Connect Stripe or another PSP for live charge capture and payouts.',
  },
  {
    channel: 'audit',
    status: 'ready',
    note: 'Audit trail structure is defined for milestone tracking and permissions.',
  },
  {
    channel: 'qr',
    status: 'ready',
    note: 'QR ticket issuance and scan lifecycle are scaffolded in the platform model.',
  },
  {
    channel: 'check_in',
    status: 'needs_config',
    note: 'Offline sync and mobile scanning device registration still to be wired.',
  },
];

export const orgSettings: OrgSettings = {
  orgId: 'org_eventhub_nz',
  emailSender: '',
  paymentProvider: '',
  emailProvider: '',
  qrIssuerKey: '',
  auditWebhook: '',
};

export const integrationConnections: IntegrationConnection[] = [
  {
    id: 'int_001',
    kind: 'crm',
    name: 'Salesforce contact sync',
    provider: 'Salesforce',
    status: 'needs_config',
    syncMode: 'bidirectional',
    notes: 'Ready for lead and attendee sync once credentials are added.',
  },
  {
    id: 'int_002',
    kind: 'accounting',
    name: 'Xero revenue export',
    provider: 'Xero',
    status: 'degraded',
    syncMode: 'push',
    lastSyncAt: '2026-04-18 19:20',
    notes: 'Awaiting refreshed tenant token after sandbox expiry.',
  },
  {
    id: 'int_003',
    kind: 'sso',
    name: 'Organizer SSO',
    provider: 'Okta',
    status: 'needs_config',
    syncMode: 'pull',
    notes: 'SCIM and SAML configuration still pending.',
  },
];

export const webhookEndpoints: WebhookEndpoint[] = [
  {
    id: 'hook_001',
    label: 'Accounting export listener',
    url: 'https://hooks.eventhub.local/accounting',
    subscribedEvents: ['order.paid', 'order.refunded', 'payout.reconciled'],
    status: 'active',
    lastDeliveryAt: '2026-04-19 21:48',
  },
  {
    id: 'hook_002',
    label: 'CRM enrichment',
    url: 'https://hooks.eventhub.local/crm',
    subscribedEvents: ['ticket.issued', 'checkin.admitted'],
    status: 'paused',
  },
];

export const apiCredentials: ApiCredential[] = [
  {
    id: 'cred_001',
    label: 'Marketing warehouse read key',
    scope: 'read_only',
    createdAt: '2026-04-10 10:00',
    lastUsedAt: '2026-04-19 17:00',
    status: 'active',
  },
  {
    id: 'cred_002',
    label: 'Venue ops admin key',
    scope: 'admin',
    createdAt: '2026-04-03 09:15',
    lastUsedAt: '2026-04-18 14:20',
    status: 'active',
  },
];

export const financeExports: FinanceExport[] = [
  {
    id: 'fin_001',
    kind: 'orders',
    provider: 'Xero',
    periodLabel: 'April 2026 MTD',
    status: 'ready',
    rowCount: 388,
    amount: 34672,
    createdAt: '2026-04-19 22:05',
  },
  {
    id: 'fin_002',
    kind: 'reconciliation',
    provider: 'Stripe',
    periodLabel: 'Week ending 19 Apr 2026',
    status: 'processing',
    rowCount: 112,
    amount: 58210,
    createdAt: '2026-04-19 21:40',
  },
];

export const reconciliationRuns: ReconciliationRun[] = [
  {
    id: 'rec_001',
    provider: 'Stripe',
    periodLabel: 'Week ending 19 Apr 2026',
    matchedCount: 108,
    unmatchedCount: 4,
    varianceAmount: 136,
    status: 'review',
    createdAt: '2026-04-19 21:55',
  },
  {
    id: 'rec_002',
    provider: 'Xero',
    periodLabel: 'March 2026 close',
    matchedCount: 224,
    unmatchedCount: 0,
    varianceAmount: 0,
    status: 'completed',
    createdAt: '2026-04-01 08:30',
  },
];

export const taxProfiles: TaxProfile[] = [
  {
    id: 'tax_001',
    region: 'New Zealand',
    registrationNumber: 'NZBN-9429041234567',
    defaultRate: 15,
    filingCadence: 'monthly',
    pricesIncludeTax: true,
  },
  {
    id: 'tax_002',
    region: 'Australia',
    registrationNumber: 'ABN-51-824-753-556',
    defaultRate: 10,
    filingCadence: 'quarterly',
    pricesIncludeTax: true,
  },
];

export const managedOrganizations: ManagedOrganization[] = [
  {
    id: 'org_eventhub_nz',
    name: 'EventHub Pacific',
    region: 'NZ / AU',
    activeEvents: 6,
    revenue: 973740,
    teamCount: 4,
    complianceStatus: 'healthy',
  },
  {
    id: 'org_partner_001',
    name: 'South Coast Venues',
    region: 'Australia',
    activeEvents: 3,
    revenue: 182400,
    teamCount: 11,
    complianceStatus: 'attention',
  },
];

export const ssoConfigurations: SsoConfiguration[] = [
  {
    provider: 'Okta',
    domain: 'organizers.eventhub.io',
    status: 'pending',
    enforced: false,
  },
];

export const sessions: SessionRecord[] = [
  {
    id: 'sess_001',
    eventId: 'evt_005',
    title: 'Design systems in the wild',
    track: 'Product',
    startsAt: '2026-08-20 10:00',
    endsAt: '2026-08-20 10:45',
    speakerIds: ['spk_001'],
    room: 'Main Stage',
    capacity: 240,
  },
  {
    id: 'sess_002',
    eventId: 'evt_005',
    title: 'Brand storytelling for scaling teams',
    track: 'Brand',
    startsAt: '2026-08-20 11:15',
    endsAt: '2026-08-20 12:00',
    speakerIds: ['spk_002'],
    room: 'Studio One',
    capacity: 120,
  },
];

export const speakers: SpeakerProfile[] = [
  {
    id: 'spk_001',
    name: 'Amelia Hart',
    title: 'Design Director',
    organization: 'North Studio',
    bio: 'Design systems leader working across product, service design, and governance.',
    topicTags: ['design systems', 'product', 'operations'],
  },
  {
    id: 'spk_002',
    name: 'Jared Tuivasa',
    title: 'Brand Strategist',
    organization: 'Signal Advisory',
    bio: 'Helps growth-stage teams align brand, story, and product launch strategy.',
    topicTags: ['brand', 'storytelling', 'go-to-market'],
  },
];

export const sponsors: SponsorProfile[] = [
  {
    id: 'spr_001',
    eventId: 'evt_005',
    name: 'North Studio',
    tier: 'headline',
    boothId: 'booth_001',
    website: 'https://northstudio.example',
  },
  {
    id: 'spr_002',
    eventId: 'evt_005',
    name: 'Signal Advisory',
    tier: 'gold',
    boothId: 'booth_002',
    website: 'https://signal.example',
  },
];

export const exhibitorBooths: ExhibitorBooth[] = [
  {
    id: 'booth_001',
    eventId: 'evt_005',
    name: 'North Studio',
    hall: 'Expo Hall A',
    boothCode: 'A12',
    leadCount: 84,
    meetingCount: 16,
  },
  {
    id: 'booth_002',
    eventId: 'evt_005',
    name: 'Signal Advisory',
    hall: 'Expo Hall A',
    boothCode: 'A18',
    leadCount: 53,
    meetingCount: 12,
  },
];

export const matchmakingProfiles: MatchmakingProfile[] = [
  {
    id: 'mm_001',
    eventId: 'evt_005',
    attendeeName: 'Leah Thompson',
    interests: ['design systems', 'leadership'],
    goals: ['find collaborators', 'meet sponsors'],
    availability: 'Day 1 afternoon',
  },
  {
    id: 'mm_002',
    eventId: 'evt_005',
    attendeeName: 'Finn Roberts',
    interests: ['brand', 'product design'],
    goals: ['book mentor session'],
    availability: 'Day 2 morning',
  },
];

export const appointments: AppointmentRecord[] = [
  {
    id: 'appt_001',
    eventId: 'evt_005',
    attendeeName: 'Leah Thompson',
    counterpart: 'North Studio',
    startsAt: '2026-08-20 14:30',
    location: 'Meeting Lounge 2',
    status: 'scheduled',
  },
];

export const livePolls: LivePoll[] = [
  {
    id: 'poll_001',
    eventId: 'evt_005',
    question: 'Which workflow creates the most team friction right now?',
    status: 'live',
    responses: 142,
  },
];

export const surveys: SurveyRecord[] = [
  {
    id: 'sur_001',
    eventId: 'evt_005',
    title: 'Design Forward attendee feedback',
    audience: 'attendees',
    completionRate: 0.48,
  },
  {
    id: 'sur_002',
    eventId: 'evt_005',
    title: 'Sponsor ROI check-in',
    audience: 'sponsors',
    completionRate: 0.67,
  },
];

export const announcements: AnnouncementRecord[] = [
  {
    id: 'ann_001',
    eventId: 'evt_005',
    title: 'Workshop rooms now open',
    channel: 'push',
    sentAt: '2026-08-20 08:55',
  },
  {
    id: 'ann_002',
    eventId: 'evt_005',
    title: 'Networking dinner venue change',
    channel: 'email',
    sentAt: '2026-08-20 17:10',
  },
];

export const resaleListings: ResaleListing[] = [
  {
    id: 'res_001',
    eventId: 'evt_001',
    ticketId: 'tkt_0001',
    sellerEmail: 'leah@example.com',
    askingPrice: 98,
    faceValue: 89,
    status: 'listed',
  },
];

export const upgradeOffers: UpgradeOffer[] = [
  {
    id: 'upg_001',
    eventId: 'evt_001',
    name: 'GA to VIP Deck',
    targetTierId: 'tier_002',
    upgradePrice: 75,
    inventory: 40,
    claimed: 12,
  },
];

export const membershipPlans: MembershipPlan[] = [
  {
    id: 'mem_001',
    name: 'EventHub First Access',
    price: 15,
    billingCycle: 'monthly',
    benefits: ['Priority onsale windows', 'Member-only offers', 'Express checkout'],
    activeMembers: 284,
  },
];

export const sponsorPlacements: SponsorPlacement[] = [
  {
    id: 'plc_001',
    eventId: 'evt_001',
    name: 'Homepage hero companion',
    placement: 'homepage',
    sponsor: 'North Studio',
    impressions: 24000,
    clicks: 512,
  },
  {
    id: 'plc_002',
    eventId: 'evt_005',
    name: 'Checkout partner panel',
    placement: 'checkout',
    sponsor: 'Signal Advisory',
    impressions: 6200,
    clicks: 198,
  },
];

export const dynamicPricingRules: DynamicPricingRule[] = [
  {
    id: 'dyn_001',
    eventId: 'evt_001',
    tierId: 'tier_001',
    trigger: 'inventory',
    adjustmentType: 'increase_percent',
    adjustmentValue: 8,
    status: 'active',
  },
];

export const customerSegments: CustomerSegment[] = [
  {
    id: 'seg_001',
    name: 'High-value repeat buyers',
    criteria: '2+ paid orders and lifetime spend above $400',
    memberCount: 186,
    repeatBuyerCount: 186,
    highValueCount: 186,
    notes: 'Best segment for VIP and presale releases.',
  },
  {
    id: 'seg_002',
    name: 'Conference decision makers',
    criteria: 'Corporate email domains and conference ticket purchases',
    memberCount: 92,
    repeatBuyerCount: 31,
    highValueCount: 24,
    notes: 'Warm audience for B2B launches and summit announcements.',
  },
  {
    id: 'seg_003',
    name: 'Lapsed festival audience',
    criteria: 'No purchase in last 180 days, prior festival attendance',
    memberCount: 541,
    repeatBuyerCount: 117,
    highValueCount: 40,
    notes: 'Use SMS urgency and early bird offers to reactivate.',
  },
];

export const campaigns: Campaign[] = [
  {
    id: 'cmp_001',
    eventId: 'evt_001',
    name: 'Summer Series final push',
    channel: 'email',
    segmentId: 'seg_001',
    status: 'scheduled',
    subject: 'Last release for Auckland Summer Series',
    scheduledAt: '2026-04-21 09:00',
    sentCount: 0,
    openRate: 0,
    clickRate: 0,
    conversionRate: 0,
    sourceTag: 'email-final-push',
    createdAt: '2026-04-18 11:00',
  },
  {
    id: 'cmp_002',
    eventId: 'evt_007',
    name: 'Dusk to Dawn SMS urgency',
    channel: 'sms',
    segmentId: 'seg_003',
    status: 'completed',
    subject: 'Doors 10PM. Final release now live.',
    scheduledAt: '2026-04-16 18:00',
    sentCount: 420,
    openRate: 0.96,
    clickRate: 0.29,
    conversionRate: 0.11,
    sourceTag: 'sms-d2d-final',
    createdAt: '2026-04-15 12:30',
  },
  {
    id: 'cmp_003',
    eventId: 'evt_005',
    name: 'Design Forward partner invite',
    channel: 'email',
    segmentId: 'seg_002',
    status: 'draft',
    subject: 'Invite your team to Design Forward Summit',
    sentCount: 0,
    openRate: 0,
    clickRate: 0,
    conversionRate: 0,
    sourceTag: 'partner-invite',
    createdAt: '2026-04-17 09:45',
  },
];

export const discountCampaigns: DiscountCampaign[] = [
  {
    id: 'disc_001',
    eventId: 'evt_005',
    name: 'Design Forward early bird',
    code: 'EARLY20',
    type: 'early_bird',
    amount: 20,
    startsAt: '2026-04-20 09:00',
    endsAt: '2026-05-10 23:59',
    redemptions: 74,
    revenueAttributed: 14800,
    active: true,
    createdAt: '2026-04-10 08:00',
  },
  {
    id: 'disc_002',
    eventId: 'evt_001',
    name: 'Fan club loyalty code',
    code: 'LOYAL15',
    type: 'percentage',
    amount: 15,
    redemptions: 112,
    revenueAttributed: 9520,
    active: true,
    createdAt: '2026-04-11 09:15',
  },
];

export const referralLinks: ReferralLink[] = [
  {
    id: 'ref_001',
    eventId: 'evt_001',
    label: 'Instagram creator drop',
    code: 'ig-creator-drop',
    source: 'instagram',
    clicks: 1840,
    conversions: 136,
    revenueAttributed: 12104,
    createdAt: '2026-04-12 10:00',
  },
  {
    id: 'ref_002',
    eventId: 'evt_005',
    label: 'Partner newsletter',
    code: 'partner-newsletter',
    source: 'email',
    clicks: 422,
    conversions: 41,
    revenueAttributed: 8200,
    createdAt: '2026-04-14 09:00',
  },
];

export const checkoutQuestions: CheckoutQuestion[] = [
  {
    id: 'qform_001',
    eventId: 'evt_005',
    label: 'Dietary requirements',
    type: 'text',
    required: false,
  },
  {
    id: 'qform_002',
    eventId: 'evt_005',
    label: 'Primary discipline',
    type: 'select',
    required: true,
    options: ['Product design', 'Brand', 'Engineering', 'Marketing', 'Leadership'],
  },
  {
    id: 'qform_003',
    eventId: 'evt_001',
    label: 'Join the fan list for first release alerts',
    type: 'checkbox',
    required: false,
  },
];

export const conversionReports: ConversionReport[] = [
  {
    id: 'conv_001',
    eventId: 'evt_001',
    scope: 'event',
    windowLabel: 'Last 7 days',
    visits: 12480,
    checkoutStarts: 1432,
    ordersCompleted: 388,
    revenue: 34672,
    topSource: 'instagram',
    updatedAt: '2026-04-19 22:00',
  },
  {
    id: 'conv_002',
    eventId: 'evt_005',
    scope: 'event',
    windowLabel: 'Last 30 days',
    visits: 5320,
    checkoutStarts: 740,
    ordersCompleted: 198,
    revenue: 39600,
    topSource: 'partner-email',
    updatedAt: '2026-04-19 22:00',
  },
  {
    id: 'conv_003',
    scope: 'organization',
    windowLabel: 'Portfolio MTD',
    visits: 44210,
    checkoutStarts: 4282,
    ordersCompleted: 1102,
    revenue: 142360,
    topSource: 'organic',
    updatedAt: '2026-04-19 22:00',
  },
];

export const dashboardStats = {
  liveRevenue: events.reduce((t, e) => t + e.grossRevenue, 0),
  activeEvents: events.filter((e) => e.status === 'on_sale' || e.status === 'live').length,
  venuesOnline: venues.length,
  scansToday: checkpoints.reduce((t, c) => t + c.scanned, 0),
};

export const eventNameById = Object.fromEntries(events.map((e) => [e.id, e.name]));
export const venueNameById = Object.fromEntries(venues.map((v) => [v.id, v.name]));

// ─── Milestone 4 — High-demand sales seed data ───────────────────────────────

export const waitingRoom: WaitingRoomEntry[] = [
  {
    id: 'q_001',
    eventId: 'evt_001',
    sessionId: 'sess_aaa111',
    buyerEmail: 'jade@example.com',
    position: 1,
    estimatedWaitMins: 2,
    status: 'releasing',
    joinedAt: '2026-04-19 09:01',
    releasedAt: '2026-04-19 09:14',
  },
  {
    id: 'q_002',
    eventId: 'evt_001',
    sessionId: 'sess_bbb222',
    buyerEmail: 'marcus@example.com',
    position: 2,
    estimatedWaitMins: 5,
    status: 'queued',
    joinedAt: '2026-04-19 09:02',
  },
  {
    id: 'q_003',
    eventId: 'evt_001',
    sessionId: 'sess_ccc333',
    position: 3,
    estimatedWaitMins: 8,
    status: 'queued',
    joinedAt: '2026-04-19 09:04',
  },
  {
    id: 'q_004',
    eventId: 'evt_004',
    sessionId: 'sess_ddd444',
    buyerEmail: 'sofia@example.com',
    position: 1,
    estimatedWaitMins: 3,
    status: 'queued',
    joinedAt: '2026-04-19 09:10',
  },
];

export const inventoryHolds: InventoryHold[] = [
  {
    id: 'hold_001',
    eventId: 'evt_001',
    tierId: 'tier_001',
    quantity: 4,
    holderId: 'sess_aaa111',
    status: 'active',
    createdAt: '2026-04-19 09:14',
    expiresAt: '2026-04-19 09:24',
  },
  {
    id: 'hold_002',
    eventId: 'evt_001',
    tierId: 'tier_002',
    quantity: 2,
    holderId: 'sess_eee555',
    status: 'active',
    createdAt: '2026-04-19 09:10',
    expiresAt: '2026-04-19 09:20',
  },
  {
    id: 'hold_003',
    eventId: 'evt_004',
    tierId: 'tier_004',
    quantity: 2,
    holderId: 'sess_fff666',
    status: 'converted',
    createdAt: '2026-04-19 08:55',
    expiresAt: '2026-04-19 09:05',
    convertedToOrderId: 'ord_1001',
  },
];

export const purchaseLimits: PurchaseLimitRule[] = [
  {
    id: 'limit_001',
    eventId: 'evt_001',
    maxPerOrder: 6,
    maxPerBuyer: 8,
    notes: 'Auckland Summer Series — general limit',
  },
  {
    id: 'limit_002',
    eventId: 'evt_001',
    tierId: 'tier_002',
    maxPerOrder: 2,
    maxPerBuyer: 2,
    notes: 'VIP Deck — strictly 2 per buyer to prevent resale',
  },
  {
    id: 'limit_003',
    eventId: 'evt_004',
    maxPerOrder: 4,
    maxPerBuyer: 6,
    notes: 'Pacific Groove Festival',
  },
];

export const presaleCodes: PresaleCode[] = [
  {
    id: 'code_001',
    eventId: 'evt_001',
    code: 'FANCLUB26',
    label: 'Fan Club — Wave 1',
    allowedTierIds: ['tier_001', 'tier_002'],
    maxUses: 500,
    usedCount: 312,
    status: 'active',
    validFrom: '2026-04-10 09:00',
    validUntil: '2026-05-01 23:59',
    createdAt: '2026-04-09 14:00',
  },
  {
    id: 'code_002',
    eventId: 'evt_001',
    code: 'PRESS2026',
    label: 'Press & Industry',
    allowedTierIds: [],
    maxUses: 50,
    usedCount: 12,
    status: 'active',
    createdAt: '2026-04-12 10:00',
  },
  {
    id: 'code_003',
    eventId: 'evt_004',
    code: 'PACIFIC24',
    label: 'Pacific Groove — Early Access',
    allowedTierIds: ['tier_004'],
    maxUses: 200,
    usedCount: 200,
    status: 'exhausted',
    validFrom: '2026-04-01 09:00',
    validUntil: '2026-04-15 23:59',
    createdAt: '2026-03-28 09:00',
  },
];

export const priorityGroups: PriorityGroup[] = [
  {
    id: 'pgroup_001',
    eventId: 'evt_001',
    name: 'Fan Club Members',
    accessLevel: 'presale_early',
    allowedTierIds: ['tier_001', 'tier_002'],
    memberCount: 1840,
    notes: 'Access opens 48h before general public',
    createdAt: '2026-04-01 09:00',
  },
  {
    id: 'pgroup_002',
    eventId: 'evt_001',
    name: 'Press & Industry',
    accessLevel: 'presale_code',
    allowedTierIds: [],
    memberCount: 50,
    notes: 'Requires PRESS2026 code',
    createdAt: '2026-04-05 10:00',
  },
  {
    id: 'pgroup_003',
    eventId: 'evt_004',
    name: 'Pacific Groove VIP List',
    accessLevel: 'presale_early',
    allowedTierIds: ['tier_005'],
    memberCount: 300,
    notes: 'Priority access to VIP wristbands',
    createdAt: '2026-03-20 09:00',
  },
];

export const fraudFlags: FraudFlag[] = [
  {
    id: 'flag_001',
    eventId: 'evt_001',
    orderId: 'ord_1001',
    buyerEmail: 'leah@example.com',
    flagType: 'bulk_purchase',
    severity: 'medium',
    detail: 'Order of 4 tickets — possible resale. Buyer has no prior history.',
    detectedAt: '2026-04-19 18:10',
    resolved: false,
  },
  {
    id: 'flag_002',
    eventId: 'evt_001',
    buyerEmail: 'bot_sess_x91@temp.io',
    flagType: 'bot_pattern',
    severity: 'high',
    detail: 'Session completed checkout in 3.2 seconds. Human baseline is 45s+.',
    detectedAt: '2026-04-19 09:08',
    resolved: true,
    resolvedBy: 'Tom Omaet',
    resolvedAt: '2026-04-19 09:45',
  },
  {
    id: 'flag_003',
    eventId: 'evt_004',
    buyerEmail: 'ticket_flip@resale.net',
    flagType: 'known_reseller',
    severity: 'high',
    detail: 'Email matches known resale account from previous events.',
    detectedAt: '2026-04-19 09:15',
    resolved: false,
  },
];

export const abuseEvents: AbuseEvent[] = [
  {
    id: 'abuse_001',
    eventId: 'evt_001',
    pattern: 'rapid_attempts',
    ipHash: 'sha256:4f2c1a9d',
    sessionCount: 14,
    detectedAt: '2026-04-19 09:06',
    action: 'blocked',
  },
  {
    id: 'abuse_002',
    eventId: 'evt_001',
    pattern: 'hold_farming',
    ipHash: 'sha256:7e3b0c12',
    sessionCount: 6,
    detectedAt: '2026-04-19 09:11',
    action: 'flagged',
  },
  {
    id: 'abuse_003',
    eventId: 'evt_004',
    pattern: 'code_stuffing',
    ipHash: 'sha256:2a8f4e91',
    sessionCount: 3,
    detectedAt: '2026-04-19 09:20',
    action: 'logged',
  },
];

export const queueSnapshots: QueueSnapshot[] = [
  {
    id: 'snap_001',
    eventId: 'evt_001',
    capturedAt: '2026-04-19 09:00',
    queueDepth: 1240,
    releaseRate: 80,
    attemptRate: 120,
    activeHolds: 42,
    conversionRate: 0.68,
  },
  {
    id: 'snap_002',
    eventId: 'evt_001',
    capturedAt: '2026-04-19 09:05',
    queueDepth: 1086,
    releaseRate: 90,
    attemptRate: 115,
    activeHolds: 51,
    conversionRate: 0.71,
  },
  {
    id: 'snap_003',
    eventId: 'evt_001',
    capturedAt: '2026-04-19 09:10',
    queueDepth: 843,
    releaseRate: 85,
    attemptRate: 108,
    activeHolds: 38,
    conversionRate: 0.74,
  },
  {
    id: 'snap_004',
    eventId: 'evt_001',
    capturedAt: '2026-04-19 09:15',
    queueDepth: 612,
    releaseRate: 82,
    attemptRate: 99,
    activeHolds: 29,
    conversionRate: 0.76,
  },
];

export function createSeedDatabase(): AppDatabase {
  return {
    schemaVersion: EVENTHUB_SCHEMA_VERSION,
    updatedAt: new Date().toISOString(),
    organization: currentOrganization,
    teamMembers,
    venues,
    events,
    ticketTiers,
    orders,
    issuedTickets,
    checkInScans: [],
    checkpoints,
    auditLog,
    orgSettings,
    paymentRecords: [],
    emailLogs: [],
    campaigns,
    discountCampaigns,
    referralLinks,
    checkoutQuestions,
    customerSegments,
    conversionReports,
    integrationConnections,
    webhookEndpoints,
    apiCredentials,
    financeExports,
    reconciliationRuns,
    taxProfiles,
    managedOrganizations,
    ssoConfigurations,
    sessions,
    speakers,
    sponsors,
    exhibitorBooths,
    matchmakingProfiles,
    appointments,
    livePolls,
    surveys,
    announcements,
    resaleListings,
    upgradeOffers,
    membershipPlans,
    sponsorPlacements,
    dynamicPricingRules,
    devices,
    accessRules,
    offlineQueue,
    reEntryRecords,
    waitingRoom,
    inventoryHolds,
    purchaseLimits,
    presaleCodes,
    priorityGroups,
    fraudFlags,
    abuseEvents,
    queueSnapshots,
  };
}
